name: Continuous Deployment

on:
  push:
    branches:
      - master
      - main

    jobs:
      deploy:
        name: Deploy
        runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy staging
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo main

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo CUSTOM NODE