name: CI/CD

on:
  push:
    branches: [ main, master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: yarn install
    - run: yarn run test

  deploy:
    needs: test  

    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_REGION: "${{ secrets.AWS_REGION }}"
      SOURCE_DIR: "build"

    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: yarn install
    - run: CI=false yarn run build

    - name: MAIN
      if: github.ref == 'refs/heads/main'
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: "${{ secrets.AWS_S3_MAIN_BUCKET }}"
    - run: echo $AWS_S3_BUCKET
    
    - name: MASTER
      if: github.ref == 'refs/heads/master'
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: "${{ secrets.AWS_S3_MASTER_BUCKET }}"
    - run: echo $AWS_S3_BUCKET